prometheus_server: "192.168.150.187:9090"
scales:
  - name: "Chromatic"
    intervals: [1,1,1,1,1,1,1,1,1,1,1,1]
  - name: "Ionian"
    intervals: [2,2,1,2,2,2,1]
  - name: "Dorian"
    intervals: [2,1,2,2,2,1,2]
  - name: "Phrygian"
    intervals: [1,2,2,2,1,2,2]
  - name: "Lydian"
    intervals: [2,2,2,1,2,2,1]
  - name: "Mixoloyian"
    intervals: [2,2,1,2,2,1,2]
  - name: "Aeolian"
    intervals: [2,1,2,2,1,2,2]
  - name: "Locrian"
    intervals: [1,2,2,1,2,2,2]
  - name: "Harmonic Minor"
    intervals: [2,1,2,2,1,3,1]
  - name: "Whole Tone"
    intervals: [2,2,2,2,2,2,2]
  - name: "Japanese Yo"
    intervals: [2,3,2,2,3]
  - name: "Algerian"
    intervals: [2,1,2,1,1,1,3,1]
  - name: "Algerian Long"
    intervals: [2,1,3,1,1,3,1,2,1,2]



# Scales to add:

# https://en.wikipedia.org/wiki/List_of_musical_scales_and_modes
# https://andrulianblog.wordpress.com/2014/04/14/a-list-of-unusual-scales/


# 2 - 1 - 3 - 1 - 1 - 3 - 1 - 2 - 1 - 2 (Long Version)
# Arabic:
# 2 - 2 - 1 - 1 - 2 - 2 - 2
# Augmented:
# 3 - 1 - 3 - 1 - 3 - 1
# Balinese:
#  1 - 2 - 4 - 1 - 4
# Byzantine:
#  1 - 3 - 1 - 2 - 1 - 3 - 1
# Chinese:
#  4 - 2 - 1 - 4 - 1
# Dimnished:
# 2 - 1 - 2 - 1 - 2 - 1 - 2 - 1
# DominantDiminished:
# 1 - 2 - 1 - 2 - 1 - 2 - 1 - 2
# Egyptian:
#  2 - 3 - 2 - 3 - 2
# Eight Tone Spanish:
# 1 - 2 - 1 - 1 - 1- 2 - 2 - 2
# Geez (Ethiopian):
# 2 - 1 - 2 - 2 - 1 - 2 - 2
# Hindu:
# 2 - 2 - 1 - 2 - 1 - 2 - 2
# Hirajoshi:
# 1 - 4 - 1 - 4 - 2
# Hungarian Gypsy:
# 2 - 1 - 3 - 1 - 1 - 3 - 1
# Hungarian Major:
# 3 - 1 - 2 - 1 - 2 - 1 - 2
# Japanese (in sen):
# 1 - 4 - 2 - 3 - 2
# Lydian Dominant:
# 2 - 2 - 2 - 1 - 2 - 1 - 2
# Neopolitan Minor:
# 1 - 2 - 2 - 2 - 1 - 3 - 1
# Neopolitan Major:
# 1 - 2 - 2 - 2 - 2 - 2 - 1
# Octatonic:
# 1- 2 - 1 - 2 - 1 - 2 - 1 - 2
# Oriental:
# 1 - 3 - 1 - 1 - 3 - 1 - 2
# Romanian Minor:
# 2 - 1 - 3 - 1 - 2 - 1 - 2
# Spanish Gypsy:
# 1 - 3 - 1 - 2 - 1 - 2 - 2
# Super Locrian:
# 1 - 2 - 1 - 2 - 2 - 2 - 2

