prometheus_server: "192.168.150.187:9090"
processor_config:
  default_key: "A"
  default_scale: "Algerian"
  scales:
    - name: "Chromatic"
      intervals: [1,1,1,1,1,1,1,1,1,1,1,1]
    - name: "Ionian"
      intervals: [2,2,1,2,2,2,1]
    - name: "Dorian"
      intervals: [2,1,2,2,2,1,2]
    - name: "Phrygian"
      intervals: [1,2,2,2,1,2,2]
    - name: "Lydian"
      intervals: [2,2,2,1,2,2,1]
    - name: "Mixoloyian"
      intervals: [2,2,1,2,2,1,2]
    - name: "Aeolian"
      intervals: [2,1,2,2,1,2,2]
    - name: "Locrian"
      intervals: [1,2,2,1,2,2,2]
    - name: "Harmonic Minor"
      intervals: [2,1,2,2,1,3,1]
    - name: "Whole Tone"
      intervals: [2,2,2,2,2,2,2]
    - name: "Japanese Yo"
      intervals: [2,3,2,2,3]
    - name: "Algerian"
      intervals: [2,1,2,1,1,1,3,1]
    - name: "Algerian Long"
      intervals: [2,1,3,1,1,3,1,2,1,2]
    - name: "Arabic"
      intervals: [2,2,1,1,2,2,2]
    - name: "Augmented"
      intervals: [3,1,3,1,3,1]
    - name: "Balinese"
      intervals: [1,2,4,1,4]
    - name: "Byzantine"
      intervals: [1,3,1,2,1,3,1] 
    - name: "Chinese"
      intervals: [4,2,1,4,1]
    - name: "Diminished"
      intervals: [2,1,2,1,2,1,2,1]
    - name: "Dominant Diminished"
      intervals: [1,2,1,2,1,2,1,2]
    - name: "Egyptian"
      intervals: [2,3,2,3,2]
    - name: "Eight Tone Spanish"
      intervals: [1,2,1,1,1,2,2,2]
    - name: "Geez (Ethiopian)"
      intervals: [2,1,2,2,1,2,2]
    - name: "Hindu"
      intervals: [2,2,1,2,1,2,2]
    - name: "Hirajoshi"
      intervals: [1,4,1,4,2]
    - name: "Hungarian Gypsy"
      intervals: [2,1,3,1,1,3,1]
    - name: "Hungarian Major"
      intervals: [3,1,2,1,2,1,2]
    - name: "Japanese (in sen)"
      intervals: [1,4,2,3,2]
    - name: "Lydian Dominant"
      intervals: [2,2,2,1,2,1,2]
    - name: "Neopolitan Minor"
      intervals: [1,2,2,2,1,3,1]
    - name: "Neopolitan Major"
      intervals: [1,2,2,2,2,2,1]
    - name: "Octatonic"
      intervals: [1,2,1,2,1,2,1,2]
    - name: "Oriental"
      intervals: [1,3,1,1,3,1,2]
    - name: "Romanian Minor"
      intervals: [2,1,3,1,2,1,2]
    - name: "Spanish Gypsy"
      intervals: [1,3,1,2,1,2,2]
    - name: "Super Locrian"
      intervals: [1,2,1,2,2,2,2]
    
# Scales to add:
# https://en.wikipedia.org/wiki/List_of_musical_scales_and_modes
# https://andrulianblog.wordpress.com/2014/04/14/a-list-of-unusual-scales/
